moov-io/docs

mkdocs.yml
=> Add X9 File Structure

docs/ACH_File_Structure.md
=> Ach updates

docs/ACH_File_Structure.md
Issue: https://github.com/moov-io/ach/issues/342
=> Add Batch DNE entry and addenda

docs/ACH_File_Structure.md
Issue: https://github.com/moov-io/ach/issues/343
=> docs: Add ENR Entry Detail and Addenda

docs/ACH_File_Structure.md
Issue: https://github.com/moov-io/ach/issues/344
=> docs: Add MTE, TEL, and XCK

docs/ach-server.md, mkdocs.yml
Fixes: https://github.com/moov-io/ach/issues/400
=> docs: guide for running ACH Server

docs/ofac/file-structure.md, docs/ofac/index.md
=> Initial OFAC documentation

docs/tutorials/ach-server.md
Fix for https://github.com/moov-io/docs/issues/25
@adamdecaf
=> Add detail about port forwarding when using docker for mac

docs/tutorials/ach-server.md
Issue: https://github.com/moov-io/docs/issues/27
=> tutorials: add steps for running ACH server binary

docs/fed/file-structure.md, docs/fed/index.md, mkdocs.yml
Closes # 30,
Further updates may be forth coming
=> Initial fed documentation

docs/ach/merging-files.md, mkdocs.yml
Issue: https://github.com/moov-io/ach/issues/529
=> docs/ach: quick page on merging files

docs/tutorials/paygate.md
Lets just discuss here if this needs any more additions or changes, in order to keep track of progress.
=> Add paygate tutorial

docs/ach/balanced-offset.md, mkdocs.yml
Issue: https://github.com/moov-io/ach/issues/531
=> docs/ach: add 'Balanced Offset' page

docs/ach/flatten-batches.md, mkdocs.yml
=> flatten batches

.travis.yml, Dockerfile, makefile, nginx/default.conf, nginx/nginx.conf
Our GitHub pages setup isn't working, so I'm going to deploy this image on our hosting for now.
=> build: setup an initial moov/docs:latest Docker image

docs/icl/index.md, docs/icl/intro.md
=> icl changes

docs/paygate/ach.md, docs/paygate/admin-endpoints.md, docs/paygate/index.md
Includes:
- A note on `x-user-id` HTTP header
- JSON example of SFTP upload configs (in admin HTTP endpoint)
- Example for file-based ACH upload configs
=> paygate: add and clarify from v0.7.0 release

docs/paygate/ach.md
Documentation for PR's:
- https://github.com/moov-io/paygate/pull/355
=> paygate: fill out COR/NOC section

docs/paygate/ach.md
See: https://github.com/moov-io/paygate/pull/359
=> paygate: document new ach_file_upload_errors metric

docs/ach/custom-validation.md, mkdocs.yml
Issue: https://github.com/moov-io/ach/pull/665
=> ach: add Custom Validation section

docs/customers/checks.md, docs/customers/disclaimers.md, docs/customers/documents.md, docs/customers/index.md, docs/customers/local-dev.md, docs/index.md, mkdocs.yml
Fixes: https://github.com/moov-io/docs/issues/78
=> docs/customers: initial writeup

docs/ach/create-file.md, docs/ach/index.md, docs/customers/disclaimers.md, docs/customers/documents.md, docs/customers/index.md, docs/fed/index.md, docs/icl/index.md, docs/icl/intro.md, docs/index.md, docs/paygate/admin-endpoints.md, docs/paygate/index.md, docs/watchman/index.md, docs/wire/index.md, mkdocs.yml
Looking at the docs fresh after a few days I noticed some cleanup was needed.
=> docs: misc updates, link to API docs and cleanup pages

docs/ach/custom-validation.md, mkdocs.yml
See: https://github.com/moov-io/ach/pull/709
=> docs/ach: improve custom validation section
